---
all:
  children:
    raspberry:
      hosts:
        homeraspap:
          ansible_host: 192.168.33.253
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible_ed25519
